In [1]:
import numpy as np

In [2]:
l = [3,4,5,6,7,'preeti']

In [3]:
type(l)

list

In [5]:
np.array(l)

array(['3', '4', '5', '6', '7', 'preeti'], dtype='<U11')

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [11]:
np.array([[1,2,3,4]],ndmin = 10)

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [13]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [14]:
arr = np.array([3,4,5,6])

In [15]:
arr

array([3, 4, 5, 6])

In [16]:
arr[0]

3

In [17]:
arr[0:3:2]

array([3, 5])

In [19]:
arr = np.array([[1,2],[3,4]])

In [20]:
arr

array([[1, 2],
       [3, 4]])

In [25]:
arr[1]

array([3, 4])

In [26]:
arr = np.array([[1,2],[3,4],[5,6]])

In [27]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
arr[2,1]

6

In [30]:
np.array([3,4,5,6],dtype = np.float64)

array([3., 4., 5., 6.])

In [31]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [32]:
np.asanyarray(np.mat([1,2,3,4]))

matrix([[1, 2, 3, 4]])

In [33]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [35]:
np.fromfunction(lambda i,j,k:i+j+k,(3,3,2),dtype = int)

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [ ]:
np.fromiter()

In [36]:
for i in 5:
    print(i)

TypeError: 'int' object is not iterable

In [38]:
for i in 'preeti':
    pass

In [39]:
for i in 'p':
    pass

In [40]:
for i in [2,3,4,5,5]:
    pass

In [41]:
s = 'preeti'
next(s)

TypeError: 'str' object is not an iterator

In [42]:
l = [1,2,3,4,5]

In [43]:
next(r)

NameError: name 'r' is not defined

In [44]:
s ='preeti'

In [45]:
i = iter(s)

In [46]:
next(i)

'p'

In [47]:
for i in 'preeti':
    print(i)

p
r
e
e
t
i


In [48]:
l

[1, 2, 3, 4, 5]

In [49]:
np.fromiter([1,2,3,4,5],dtype = float)

array([1., 2., 3., 4., 5.])

In [51]:
np.fromstring('22 334 45',sep = '')

<ipython-input-51-35038e732554>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('22 334 45',sep = '')


ValueError: string size must be a multiple of element size

In [52]:
arr.shape

(3, 2)

In [53]:
arr.dtype

dtype('int32')

In [56]:
list(range(0,7.6))

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0,4.6,.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5])

In [61]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [68]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.empty((3,5))

array([[0.3, 0.6, 0.9, 1.2, 1.5],
       [1.8, 2.1, 2.4, 2.7, 3. ],
       [3.3, 3.6, 3.9, 4.2, 4.5]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.random.rand(3,5,5)

array([[[0.96886859, 0.35808777, 0.53815054, 0.29814052, 0.4025847 ],
        [0.38000346, 0.72254136, 0.72400763, 0.97384843, 0.25742039],
        [0.40613369, 0.04522371, 0.71542686, 0.68629417, 0.53831226],
        [0.27011577, 0.62058891, 0.22654724, 0.72400669, 0.36595594],
        [0.04772414, 0.56607818, 0.45185251, 0.64324312, 0.10891764]],

       [[0.8829698 , 0.55285613, 0.37187516, 0.92818375, 0.65037709],
        [0.24871506, 0.64060919, 0.47531748, 0.70902128, 0.35691584],
        [0.67982868, 0.03863793, 0.74448621, 0.0234089 , 0.69607019],
        [0.5604611 , 0.33389961, 0.71025469, 0.08489024, 0.81543231],
        [0.38922916, 0.219086  , 0.07246828, 0.33921145, 0.23451778]],

       [[0.38203355, 0.29421236, 0.39501505, 0.25648468, 0.19041067],
        [0.72420268, 0.40184777, 0.62118294, 0.44403667, 0.9388634 ],
        [0.75103764, 0.81657272, 0.32091638, 0.23706252, 0.06051972],
        [0.69749348, 0.22242048, 0.97115746, 0.97288774, 0.99562091],
        [0.82732

In [75]:
np.random.randn(4,5)

array([[ 0.26617   ,  0.07895344, -1.57601359, -1.04024822,  1.58603531],
       [ 0.29349776,  2.45133704, -0.09734268,  0.02773391, -0.03495045],
       [-1.48237937,  0.4732917 ,  0.99890571, -0.11170562,  1.12881436],
       [-0.83927061, -1.97218852,  0.18990269,  0.89752517, -0.64363431]])

In [78]:
np.random.randint(3,40,size = 60)

array([32, 32, 27, 36, 17, 27, 19, 23,  6, 20, 35, 11, 30, 26,  7,  5, 24,
       10, 39, 11, 30, 20, 10, 16, 31, 25,  3,  6, 15, 13,  3, 36, 22, 32,
        6, 23, 17, 14,  7, 22, 27,  8, 33, 39, 28, 31, 37, 39,  3, 22, 11,
        8,  4, 10, 37, 15, 34, 34, 17, 38])

In [79]:
np.random.randint(2,7,(4,5))

array([[6, 2, 5, 4, 4],
       [3, 5, 6, 4, 4],
       [3, 6, 4, 6, 4],
       [3, 2, 3, 4, 3]])

In [80]:
arr.shape

(3, 2)

In [81]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
mat1 = np.random.rand(3,3)

In [85]:
mat2

NameError: name 'mat2' is not defined

In [2]:
import numpy as np

In [3]:
l = [2,3,4,56,7,34,3,'preeti']

In [4]:
type(l)

list

In [5]:
np.array(l)

array(['2', '3', '4', '56', '7', '34', '3', 'preeti'], dtype='<U11')

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [8]:
np.array([[1,2,3,4]],ndmin = 4)

array([[[[1, 2, 3, 4]]]])

In [9]:
np.array([[1,2,3,4]],ndmin = 10)   ### it will create 10 dimensional array

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [10]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [11]:
arr=np.array([2,3,4,5])

In [12]:
arr

array([2, 3, 4, 5])

In [13]:
arr[2]

4

In [14]:
arr[0::3]

array([2, 5])

In [15]:
arr[0:3:2]

array([2, 4])

In [28]:
arr = np.array([[3,4,5],[4,5,6]])

In [29]:
arr

array([[3, 4, 5],
       [4, 5, 6]])

In [31]:
arr[1][1]

5

In [33]:
np.asarray([2,3,4,5],dtype = np.float32)

array([2., 3., 4., 5.], dtype=float32)

In [34]:
np.asarray([2,3,4,5])

array([2, 3, 4, 5])

In [35]:
np.asanyarray([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [36]:
np.asanyarray(np.mat([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [7]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [8]:
np.fromfunction(lambda i,j,k:i*j*k,(3,3,3),dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [12]:
np.fromfunction(lambda i,j,k: i+j+k,(3,3,2),dtype = int)

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [13]:
np.fromfunction(lambda i,j,k: i+j+k,(3,3,1),dtype = int)

array([[[0],
        [1],
        [2]],

       [[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

In [14]:
for i in 5:
    print(i)

TypeError: 'int' object is not iterable

In [16]:
for i in 'preeti':
    print(i)


p
r
e
e
t
i


In [18]:
for i in 'preeti':
    pass

In [19]:
print(i)

i


In [20]:
for i in 'p':
    pass

In [21]:
for i in [2,3,4,5]:
    pass

In [22]:
s = 'preeti'
next(s)

TypeError: 'str' object is not an iterator

In [23]:
l = [1,2,3,4,5]
next(l)

TypeError: 'list' object is not an iterator

In [24]:
range(4)

range(0, 4)

In [25]:
r = range(4)
next(r)

TypeError: 'range' object is not an iterator

In [26]:
s = 'preeti'
i = iter(s)
next(i)

'p'

In [27]:
next(i)

'r'

In [28]:
l

[1, 2, 3, 4, 5]

In [29]:
next(l)

TypeError: 'list' object is not an iterator

In [30]:
i = iter(l)

In [32]:
next(i)

1

In [33]:
next(i)

2

In [34]:
np.fromiter([1,2,3,4,5])

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [41]:
np.fromiter([1,2,3,4,5], dtype = float)

array([1., 2., 3., 4., 5.])